services:
  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - "${POSTGRES_PORT:-54321}:5432"
    environment:
      POSTGRES_USER: "${POSTGRES_USER:-postgres}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD:-password}"
      POSTGRES_DB: "${POSTGRES_DB:-lighthouse}"
    command: ["postgres", "-N", "1000"] # Increase max connections
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER:-postgres}"]
      interval: 1s
      retries: 10
    volumes:
      - ./docker/data/postgres:/var/lib/postgresql/data

volumes:
  postgres_data:
