base_url: "http://localhost:8080"
port: 8080
host: "127.0.0.1"
database:
  driver: "postgres"
  host: "localhost"
  port: 54321
  username: "postgres"
  password: "password"
  database_name: "lighthouse"
  require_ssl: false
